server:
  port: 8088


spring:
  profiles:
    active: dev
---
server:
  port: 8087
spring:
  profiles: dev
---
server:
  port: 8086
spring:
  profiles: prod
---


#person:
  lastName: michael
  age: 18
  boss: false
  birth: 1993/08/01
  maps: {k1: v1,k2: l2}
  lists:
    - Jordan
    - Kobe
    - James
  dog:
    name: 小狗
    age: 2
---